services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - './grafana/data:/var/lib/grafana'
      - ./grafana/config/grafana:/etc/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
  local_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      INFLUXDB_DATABASE_NAME: $INFLUXDB_DATABASE_NAME
      INFLUXDB_URL: $INFLUXDB_URL
      INFLUXDB_ORG: $INFLUXDB_ORG
      INFLUXDB_TOKEN: $INFLUXDB_TOKEN
      MQTT_BROKER_URL: $MQTT_BROKER_URL
      MQTT_BROKER_PORT: $MQTT_BROKER_PORT
    depends_on:
      - mosquitto